In [6]:
import pandas as pd

players = ['김건희', '김태진', '김혜성', '도슨', '변상권', '송성문', '이용규', '이주형', '최주환']
files = ['_zone_타율.csv', '_zone_ops.csv', '_zone_컨택율.csv', '_zone_스윙율.csv']

index_list = ['타율 - ', 'OPS - ', 'Contact% - ', 'Swing% - '] 
removing_index = ['너클볼', '우언', '주자없음', '주자있음', '득점권', '구종모름']
count_index = ['초구', '스트라이크 > 볼', '볼 > 스트라이크', '스트라이크 = 볼']
fast_ball_index = ['투심', '포심', '커터']
droping_columns = ['PA_' + str(i+1) for i in range(25)]

for player in players:
    for i in range(4):
        # 파일 읽기
        df = pd.read_csv('batter_data/' + player + files[i])
        df = df.drop(columns=droping_columns)

        # 첫 번째 열의 문자열에서 index_list[i] 제거
        df.iloc[:, 0] = df.iloc[:, 0].apply(lambda x: x.replace(index_list[i], '') if index_list[i] in x else x)

        # 제거할 행 필터링 (첫 번째 열의 값이 `removing_index`에 포함된 경우)
        removing_rows = [index for index in removing_index]
        df = df[~df.iloc[:, 0].isin(removing_rows)]

        # count 행을 합쳐서 하나의 행으로 만들기
        count_rows = [index for index in count_index]
        if all(row in df.iloc[:, 0].values for row in count_rows):
            count_sum = df[df.iloc[:, 0].isin(count_rows)].iloc[:, 1:].mean()
            count_sum = count_sum.round(3)
            count_sum_row = pd.DataFrame([['카운트'] + count_sum.tolist()], columns=df.columns)
            df = pd.concat([df, count_sum_row], ignore_index=True)
            df = df[~df.iloc[:, 0].isin(count_rows)]

        # fast_ball 행을 합쳐서 하나의 행으로 만들기
        fastball_rows = [index for index in fast_ball_index]
        if all(row in df.iloc[:, 0].values for row in fastball_rows):
            fastball_sum = df[df.iloc[:, 0].isin(fastball_rows)].iloc[:, 1:].mean()
            fastball_sum = fastball_sum.round(3)
            fastball_sum_row = pd.DataFrame([['패스트볼'] + fastball_sum.tolist()], columns=df.columns)
            df = pd.concat([df, fastball_sum_row], ignore_index=True)
            df = df[~df.iloc[:, 0].isin(fastball_rows)]

        df.loc[df.iloc[:, 0] == '2S 이후', df.columns[0]] = '결정구'
        df.to_csv(player + files[i], index=False)

In [26]:
df.head()

,컨택율_1,컨택율_2,컨택율_3,컨택율_4,컨택율_5,컨택율_6,컨택율_7,컨택율_8,컨택율_9,컨택율_10,...,컨택율_16,컨택율_17,컨택율_18,컨택율_19,컨택율_20,컨택율_21,컨택율_22,컨택율_23,컨택율_24,컨택율_25
0,50.0,80.0,75.0,63.6,100.0,90.9,78.0,84.7,94.3,72.2,...,92.9,93.8,88.9,86.3,78.3,85.7,81.1,75.7,69.6,53.8
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,...,100.0,66.7,100.0,100.0,0.0,NaN,100.0,100.0,NaN,NaN
2,50.0,100.0,76.5,70.0,100.0,85.7,81.8,84.0,96.7,70.0,...,100.0,100.0,84.8,81.8,100.0,100.0,100.0,100.0,100.0,NaN
3,NaN,33.3,100.0,NaN,NaN,100.0,0.0,100.0,75.0,100.0,...,50.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0,100.0
4,NaN,100.0,NaN,0.0,NaN,NaN,100.0,100.0,100.0,NaN,...,100.0,87.5,100.0,80.0,100.0,NaN,100.0,80.0,25.0,NaN